apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: url-shortener-stage
resources:
  - namespace.yaml
  - ../../base
labels:
  - pairs:
      environment: stage
patches:
  - path: service-patch.yaml
images:
  - name: url-shortener
    newName: sunlnx/url-shortener
    newTag: stage_b30c0c1
