apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: url-shortener-dev
resources:
  - namespace.yaml
  - ../../base
labels:
  - pairs:
      environment: dev
patches:
  - path: service-patch.yaml
images:
  - name: url-shortener
    newName: sunlnx/url-shortener
    newTag: dev
