apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: url-shortener-prod
resources:
  - namespace.yaml
  - ../../base
labels:
  - pairs:
      environment: prod
patches:
  - path: service-patch.yaml
